name: 'jaffle_shop' 
config-version: '2'

profile = 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-path: ["macros"]

target-path: ["target"]
clean-teargets:
      -"target"
      - "dbt_modules"

models:
  jaffle_shop: 
    example:
      materialized: view
